import {Format as Type} from './StaticMethods';

export type Format = Type;
export {StaticMethods} from './StaticMethods';
export {default as Auth} from './Auth';
export {default as User} from './User';
export {default as Accessories} from './Accessories';
export {default as Assets} from './Assets';
export {default as Categories} from './Categories';
export {default as Companies} from './Companies';
export {default as Components} from './Components';
export {default as Consumables} from './Consumables';
export {default as Fieldsets} from './Fieldsets';
export {default as Licenses} from './Licenses';
export {default as Locations} from './Locations';
export {default as Maintenances} from './Maintenances';
export {default as Manufacturers} from './Manufacturers';
export {default as Models} from './Models';
export {default as StatusLabels} from './StatusLabels';
export {default as Activity} from './Activity';
